
# SEO
title: Jadiel Rodriguez
description: From 0 - Full Stack.

# social
social_link: twitter
social_username: JDLRODZ
github_repo: the_journey_to_engineering_ # the GitHub repo name for your project
github_username: JadielRodz
theme_color: black

# Theme
remote_theme: 'internet-de-france/swiss'
baseurl: '/JDLStatic'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


